modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "screwdrivers_plus"
version = "0.0.1"
displayName = "Screwdrivers+"
authors = "GoobleMC"
description = '''
Bringing new and exciting ways to utilise your Amethyst Screwdriver!
'''
logoFile = "../assets/screwdrivers_plus/icon.png"

[[mixins]]
config = "screwdrivers_plus_common.mixin.json"

[[mixins]]
config = "screwdrivers_plus_forge.mixin.json"

[[dependencies.screwdrivers_plus]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.screwdrivers_plus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.screwdrivers_plus]]
modId = "tardis_refined"
mandatory = true
versionRange = "[2.1.5,)"
ordering = "AFTER"
side = "BOTH"